fix: Normalize location path to avoid multiple forward slashes & fix docs
nginx/nginx-s3-gateway pull request #99
Opened 2023-02-27 15:14 UTC by dav-pascual

Fixes: https://github.com/nginxinc/nginx-s3-gateway/issues/88 and docs

2023-02-28 17:30 UTC, dekobon requested changes
Thank you for this PR! The integration tests are failing with the new changes. Can you please modify the integration tests such that they test for the new functionality?

2023-03-03 04:13 UTC, dekobon commented
I've been doing some research on how to fix the integration tests and I've been unable to find a method of normalizing slashes using rewrite rules that will preserve the requested schema, hostname, and port. I think we may have to implement this in njs. I did a prototype in njs and it was relatively simple to normalize the uri requested to S3, but it does not result in a HTTP 302 redirect to the client. I'll update as I discover more.

2023-03-03 15:06 UTC, dav-pascual commented
I have not taken a a look yet at the integration tests yet, but if the njs solution serves the content correctly even if it doesn't rewrite the URL  / redirect in the client I think that's a valid solution.

In a previous unsuccessful attempt in njs I was getting 404 errors after normalising "uri_path" variable.

2023-03-06 21:39 UTC, dav-pascual commented
I tried updating the integration tests to expect a 302 code redirect when there is a double slash, but I am getting a error code return 7 from the run, without much detail

2023-03-08 08:29 UTC, dekobon commented
@dav-pascual - I'm traveling right now, so it will be a while until I can engage on this.

2023-03-25 16:25 UTC, violethaze74 reviewed
reviewed

2026-08-17 23:18 UTC, dekobon commented
Thank you for this contribution, and apologies for closing it after such a long time. We're closing it as part of a cleanup of stale PRs: the review discussion concluded that rewrite-based slash normalization can't preserve the requested scheme, host, and port, so this needs an njs-based implementation instead, and the docs/Dockerfile.unprivileged rename portion of this PR has already landed separately. The underlying double-slash issue is still real, so a fresh PR taking the njs approach would be very welcome.

2026-08-17 23:18 UTC, closed without merging